fix issue449: push to pypi broke again due to a changed reply.
